# Site settings
title: ming-tang.github.io
description: > # this means to ignore newlines until "baseurl:"
  Guide to my GitHub.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ming-tang.github.io" # the base hostname & protocol for your site
github_username:  Ming-Tang

# Build settings
markdown: kramdown
